print("Hi there!")
name = input("What is your name? ")
print("Hello, " + name + ".")
city = input("Where are you located? ")
restaurant = input("What is your favourite restaurant in " + city + "? ")
print(restaurant + " is a great place to eat!")
starter = input("What is your favourite starter? ")
main = input("What is your go-to main dish? ")
desert = input("If you can squeeze in desert, what do you go for? ")
drink = input("And what do you have to wash it all down with? ")
print("Your favourite meal is " + starter + ", " + main + ", " + desert + " and a glass of " + drink + " at " + restaurant + ".")
